name: Build and Test

on: 
  push:
    branches:    
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3      
        with:
          fetch-depth: 0    

      - uses: paulhatch/semantic-version@v4.0.2
        name: Calculate version
        with:  
          tag_prefix: "v"          
          major_pattern: "(MAJOR)"          
          minor_pattern: "(MINOR)"          
          format: "${major}.${minor}.${patch}"
        id: calculate_version #comments 1234678900000012334440000007777

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ steps.calculate_version.outputs.version }}"
          message: "v${{ steps.calculate_version.outputs.version }}"